---
title: "β-cells cis-regulatory networks and type 1 diabetes"
subtitle: Supplementary code and analyses
author: Mireia Ramos-Rodríguez
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    code_folding: "none"
workflowr: 
  sessioninfo: "" 
---


This website contains a compendium of the code and analyses developed to obtain the results summarized in my PhD thesis (*see [About](about.html) for more information*).

## Results

Results are structured in three main publications that correspond to the following menu items:

1. <mark>**IFN-$\alpha$** to model early insulitis</mark>. In this publication, we modeled **early insulitis** by exposing human $\beta$ cells to IFN-$\alpha$ at different time points (2, 8 and 24 hours). 
We assayed and integrated multi-omic data to pinpoint the key players in inducing the $\beta$-cell interferon signature.
Finally, we selected some potential drug interventions to reverse this signature in human islets and $\beta$ cells.

> Colli, M.L., **Ramos-Rodríguez, M.**, Nakayasu, E.S. et al. An integrated multi-omics approach identifies the landscape of interferon-α-mediated responses of human pancreatic beta cells. *Nat Commun* **11**, 2584 (2020). https://doi.org/10.1038/s41467-020-16327-0

2.  <mark>**IFN-$\gamma$ + IL-1$\beta$** to model late insulitis</mark>. Similarly to the above, in this article we published multi-omics data obtained by exposing for 48 hours human pancreatic islets and human $\beta$ cells to IFN-$\gamma$ and IL-1$\beta$.
By integrating the generated data, we were able to dissect $\beta$-cell regulatory networks, possibly responding to a **late insulitis** stage.
Moreover, we observed an enrichment of T1D-associated SNPs in regulatory elements that were induced by the cytokine exposure.
We validated the functional role for two of these variants, by showing that the T1D risk alleles alter the cytokine-responsive enhancer activity in $\beta$ cells.

> **Ramos-Rodríguez, M.**, Raurell-Vila, H., Colli, M.L. et al. The impact of proinflammatory cytokines on the β-cell regulatory landscape provides insights into the genetics of type 1 diabetes. *Nat Genet.* **51**, 1588–1595 (2019) https://doi.org/10.1038/s41588-019-0524-6

3. <mark>The Islet Regulome Browser (**IRB**)</mark>. This last publication describes the implementation of the Islet Regulome Browser, an interactive online application that provides access and an integrated visualization to many genomic datasets relevant to the pancreatic islet community. 
The Islet Regulome Browser was developed with the aim of facilitating access and exploration of complex genomic data to scientists with no bioinformatic background.

> Mularoni L., **Ramos-Rodríguez M.** and Pasquali L. The Pancreatic Islet Regulome Browser. *Front. Genet.* **8** (2017). https://doi.org/10.3389/fgene.2017.00013


